##############################################################################
# Secret â€” DB credentials for accounts service and PostgreSQL pod
# Values are base64-encoded:
#   echo -n 'postgres' | base64  =>  cG9zdGdyZXM=
#   echo -n 'accounts_db'| base64 => YWNjb3VudHNfZGI=
# DATABASE_URI base64:
#   echo -n 'postgresql://postgres:postgres@postgresql:5432/accounts_db' | base64
##############################################################################
apiVersion: v1
kind: Secret
metadata:
  name: accounts-secret
type: Opaque
data:
  database-user: cG9zdGdyZXM=          # postgres
  database-password: cG9zdGdyZXM=      # postgres
  database-name: YWNjb3VudHNfZGI=      # accounts_db
  database-uri: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzcWw6NTQzMi9hY2NvdW50c19kYg==
